map_type: costmap
# CANNOT USE TAB FOR SPACING IN YAML FILES TO MAINTAIN PORTABILITY
obstacle_range: 1.0 # 2.0 1.0
raytrace_range: 1.5 # 3.0 2.0

# use larger value if you receive warning on 'Transform Timeout' and 'Map Update Loop'
transform_tolerance: 0.3 # 0.0 0.2

robot_radius: 0.05 # 0.0 0.3 0.25
inflation_radius: 0.03 # 0.0 0.5 0.26
cost_scaling_factor: 10.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /my_robot/laser/scan, marking: true, clearing: true}
